### ISSUE TITLE
Limit number of sessions

### ISSUE THREAD

**Issue by daaku** [LearnBoost/soda#24]
Maybe this doesn't belong in the library itself, but is there any way to limit the number of concurrent browser sessions when running the tests locally? I'm running the tests using expresso (https://github.com/nshah/rell/blob/master/tests.js), but each test I add ends up creating a new browser instance in parallel. If such a feature doesn't exist, would you guys be open to a patch?

**Comment by tj** [comment]
yeah sure, definitely welcome to contribute, we dont have any way to limit right now

**Comment by paulbjensen** [comment]
Hi @daaku,

Did you try using [browser.testComplete](https://github.com/LearnBoost/soda#actions) after running each test?

A limit might be a good idea - that way we can catch people when they spin up too many browser instances, and suggest that function to them.
