### ISSUE TITLE
getTitle included a bad session ID

### ISSUE THREAD

**Issue by tiefenb** [LearnBoost/soda#29]
i get in every test with the getTitle function this error:

markus-imac:saucelabs markus$ node example-test.js
 getNewBrowserSession: {"url":"http://example.saucelabs.com/","username":"*******","access-key":"*********","os":"Windows 2003","browser":"firefox","browser-version":"7","name":"This is an example test"}, http://example.saucelabs.com/
 open: /
 getTitle: 

/Users/markus/saucelabs/example-test.js:27
    if (err) throw err;
             ^
AssertionError: Title did not include the query
    at /Users/markus/saucelabs/example-test.js:23:12
    at /Users/markus/node_modules/soda/lib/soda/client.js:219:11
    at IncomingMessage.<anonymous> (/Users/markus/node_modules/soda/lib/soda/client.js:126:9)
    at IncomingMessage.emit (events.js:81:20)
    at HTTPParser.onMessageComplete (http.js:133:23)
    at Client.onData [as ondata](http.js:1488:27)
    at Client._onReadable (net.js:683:27)
    at IOWatcher.onReadable [as callback](net.js:177:10)
markus-imac:saucelabs markus$

if i log title in the getTitle function i get: "The command you just sent (getTitle) included a bad session ID.  Usually this is due to an ignored error message in an earlier command."

**Comment by ddopson** [comment]
Why was this closed?  I am having the exact same issue.
