### ISSUE TITLE
Soda and Chrome - How to set Command Line Flag --disable-web-security

### ISSUE THREAD

**Issue by sebastianwoinar** [LearnBoost/soda#30]
Hey, 
changing the browser option from "_firefox" to "_googlechrome" brings up chrome, but doesn't run the commands and throws the following error:

"error(1320828907344): isNewPageLoaded found an old pageLoadError: TypeError: Cannot call method 'indexOf' of undefined"

I found on the selenium mailing list, that this is "only" a security issue - chrome blocks cross domain interactions. This can be deactivated by setting a command line flag ("--disable-web-security").

But, where can I set it using soda? Is there any field in the options object?

Thanks!

BTW:
Here is the link to the discussion on the mailing list:
http://groups.google.com/group/selenium-users/browse_thread/thread/d9fd7cfce23351c4/d45c990ee56b8f37?lnk=gst&q=isNewPageLoaded+found+an+old+pageLoadError%3A+TypeError%3A+Cannot+call+method+%27indexOf%27+of+undefined#d45c990ee56b8f37

**Comment by tj** [comment]
hmm not too sure, I remember having a few issues getting anything but firefox to work correctly

**Comment by sebastianwoinar** [comment]
It works fine, if the binaries of the selenium-standalone-server include the command-line-argument. 
In the current version this flag is still off, but the sources in the trunk already have this change. 

So with every version > 2.11 it should work like a charm.

Thanks!
