### ISSUE TITLE
install via npm causes error: Failed to create ../.cache/soda/0.0.2/package.tgz

### ISSUE THREAD

**Issue by josue** [LearnBoost/soda#7]
Error output below:

user@~/apps/npm.git $ npm install soda
npm info it worked if it ends with ok
npm info version 0.2.0
npm info fetch http://registry.npmjs.org/soda/-/soda-0.0.2.tgz
npm ERR! Error installing soda@0.0.2
npm ERR! Error: Failed to create /usr/local/lib/node/.npm/.cache/soda/0.0.2/package.tgz: ENOENT, No such file or directory '/usr/local/lib/node/.npm/.cache/soda/0.0.2/package.tgz'
npm ERR!     at /usr/local/lib/node/.npm/npm/0.2.0/package/lib/utils/fetch.js:23:25
npm ERR!     at cb (/usr/local/lib/node/.npm/npm/0.2.0/package/lib/utils/graceful-fs.js:28:9)
npm ERR!     at node.js:759:9
npm ERR! try running: 'npm help install'
npm ERR! Report this _entire_ log at http://github.com/isaacs/npm/issues
npm ERR! or email it to npm-@googlegroups.com
npm not ok

**Comment by tj** [comment]
is this resolved? this should have nothing to do with soda

**Comment by josue** [comment]
i got it resolved but dont remember what i did to fix it. thx.
